# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-riboseq-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - picard=2.18.27
  - rseqc=2.6.2
  - samtools=1.6
  - subread=1.6.4
  - multiqc=1.7
  - bowtie2=2.3.5
  - bowtie=1.2.2
  - trimmomatic=0.39
  - igvtools=2.5.3
  - bedtools=2.27.1
  - fastx_toolkit=0.0.14
  - ucsc-wigToBigWig=366
  - pandas=0.22.0
  - ucsc-fatotwobit=377
  - argparse=1.4.0
  - pysam=0.13
  - scipy=1.0.1
  - statsmodels=0.9.0
  - twobitreader=3.1.4
  - pathos=0.2.1
  - matplotlib=2.2.2
  - seaborn=0.9.0
  - logomaker=0.8
  - scikit-learn=0.20.3
  - r-ggplot2=2.2.1
  - r-plyr=1.8.4
  - r-reshape2=1.4.3
  - r-scales=0.5.0
  - xtail=1.1.5
  - r-glue=1.3.1